# Generated by Django 5.0.6 on 2024-05-24 19:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_authormodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='test_editor',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
