# Generated by Django 5.0.6 on 2024-05-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_productscategorymodel_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='productscategorymodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.productscategorymodel'),
        ),
        migrations.AlterField(
            model_name='productsmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.productscategorymodel'),
        ),
        migrations.DeleteModel(
            name='ProductCategoryModel',
        ),
    ]
