# Generated by Django 5.0.6 on 2024-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_producttocategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsmodel',
            name='categories',
            field=models.ManyToManyField(related_name='products', to='products.productscategorymodel'),
        ),
    ]
